### PR TITLE
[bugfix] player: use userId, other fixes

### LINKED ISSUE #1928: Incorrect case in username in Subsonic API causes failure creating new player
If the username sent via the Subsonic API does not match the case of the username in the database, the user will successfully authenticate, but a new player will fail to be created.

The username in the context is set directly from the query string. This context value is what is used when creating a new player, however the player table has a foreign key constraint to the users table on username. If the case does not match, this constraint will fail.

The easy fix is to have the player registration method pull the username from the user stored in the context. A better fix might be to update the username stored in the context directly from the user model that is fetched from the database, but I am unsure if this will have any unintentional side effects when other methods will now see a "different" user based on case

### PR DESCRIPTION
**Pull request by kgarner7**
This PR primarily resolves #1928 by switching the foreign key of `player` from `user.user_name` to `user.id`. There are also a few other fixes/changes:

- For some bizarre reason, `ip_address` is never returned from `read`/`get`. Change the field to `ip`, which works. Somehow
- Update `players_test.go` mock to also check for user agent, replicating the actual code
- Update `player_repository.go` `isPermitted` to check user id. I don't know how this worked before...
- tests!
- a few places referred to `typ`, when it is really `userAgent`. Change the field names

### CODE REVIEW

File: db/migrations/20240802044339_player_use_user_id_over_username.go [hunk 1]
```diff
@@ -0,0 +1,116 @@
...
+	client varchar not null,
+	ip varchar,
+	last_seen timestamp,
+	max_bit_rate int default 0,
+	transcoding_id varchar,
+	report_real_path bool default FALSE not null,
+	scrobble_enabled bool default true
+);
+
+insert into player_dg_tmp(id, name, user_agent, user_id, client, ip, last_seen, max_bit_rate, transcoding_id, report_real_path, scrobble_enabled) select id, name, user_agent, user_name, client, ip_address, last_seen, max_bit_rate, transcoding_id, report_real_path, scrobble_enabled from player;
```
Comment (deluan) [inline db/migrations/20240802044339_player_use_user_id_over_username.go:36]: AFAICS, you are setting a username in the `player_dg_tmp.user_id` column, and you have a constraint that it should be a valid `user.id`. Is this working?

File: persistence/player_repository.go [hunk 2]
```diff
@@ -31,26 +31,33 @@ func (r *playerRepository) Put(p *model.Player) error {
 	return err
 }
 
+func (r *playerRepository) baseRequest(options ...model.QueryOptions) SelectBuilder {
```
Comment (deluan) [inline persistence/player_repository.go:34]: For consistency sake, let's call this method `selectPlayer` (see other repositories like album, artist..)

**Review by deluan — COMMENTED** [review]
This is great! Thanks for taking the time to tackle these inconsistencies. I will do some tests but from a quick glance, seems to be all good. Just check my comments below.

File: db/migrations/20240802044339_player_use_user_id_over_username.go (hunk 1 above)
Comment (kgarner7) [reply db/migrations/20240802044339_player_use_user_id_over_username.go:36]: This is handled by the later GO code (since foreign key constraints are disabled during migrations); basically, copy all the items, and either fix the username -> id, or delete it if the username doesn't exist. 
If preferred, I can convert it to an insert in Go-land (it'll just likely be mode code, mostly just for the columns). I did test the upgrade behavior myself though and see the constraints satisfied after the fact.

Comment (deluan) [reply db/migrations/20240802044339_player_use_user_id_over_username.go:36]: Ah, I see. If we don't have constraints enabled at this point, why can't we do something like this:
```sql
insert into player_dg_tmp(id, name, user_agent, user_id, client, ip, last_seen, max_bit_rate, transcoding_id, report_real_path, scrobble_enabled)
select id, name, user_agent,
       (select id from user where user_name = player.user_name),
       client, ip_address, last_seen, max_bit_rate, transcoding_id, report_real_path, scrobble_enabled from player;
delete from player_dg_tmp where user_id is null;
```

File: db/migrations/20240802044339_player_use_user_id_over_username.go [hunk 3]
```diff
@@ -0,0 +1,116 @@
...
+
+	"github.com/pressly/goose/v3"
+)
+
+func init() {
+	goose.AddMigrationContext(upPlayerUseUserIdOverUsername, downPlayerUseUserIdOverUsername)
+}
+
+func upPlayerUseUserIdOverUsername(ctx context.Context, tx *sql.Tx) error {
+	// Additional note; we also rename ip_address to IP. For some bizarre
```
Comment (deluan) [inline db/migrations/20240802044339_player_use_user_id_over_username.go:15]: I don't think this comment should be here, I think it is enough for it to be mentioned in the PR itself.

File: model/player.go [hunk 4]
```diff
@@ -21,8 +25,10 @@ type Player struct {
 type Players []Player
 
 type PlayerRepository interface {
+	rest.Persistable
+	ResourceRepository
```
Comment (deluan) [inline model/player.go:29]: Any particular reason to add these?

Comment (kgarner7) [reply model/player.go:29]: Yes; to expose the APIs for testing (and as far as I can tell, the player implements all of these methods already)

File: db/migrations/20240802044339_player_use_user_id_over_username.go (hunk 1 above)
Comment (kgarner7) [reply db/migrations/20240802044339_player_use_user_id_over_username.go:36]: That's probably a better idea. Is it guaranteed that all names exist? If not, I can still post-process, and just delete ones where the username is empty string

Comment (deluan) [reply db/migrations/20240802044339_player_use_user_id_over_username.go:34]: If I understood your question, the usernames that do not exist in the `user` table will yield a null `user_id`. Then we delete the records that have it null in the `delete` step.

Comment (kgarner7) [reply db/migrations/20240802044339_player_use_user_id_over_username.go:34]: Will that work with the `user_id varchar not null` constraint?

File: persistence/player_repository_test.go [hunk 5]
```diff
@@ -0,0 +1,257 @@
...
+
+		database = NewDBXBuilder(db.Db())
+		adminRepo = NewPlayerRepository(ctx, database)
+
+		for idx := range players {
+			err := adminRepo.Put(&players[idx])
+			Expect(err).To(BeNil())
+		}
+
+		_, err := database.NewQuery("PRAGMA foreign_keys = ON").Execute()
```
Comment (deluan) [inline persistence/player_repository_test.go:39]: I thought it was already on for all persistence tests... I think it is better to enable it at the package level, and not just for this test. You could change https://github.com/navidrome/navidrome/blob/55bff343cdaad1f04496f724eda4b55d422d7f17/persistence/persistence_suite_test.go#L24
to:
```
	conf.Server.DbPath = "file::memory:?cache=shared&_foreign_keys=on"
```

File: db/migrations/20240802044339_player_use_user_id_over_username.go (hunk 1 above)
Comment (deluan) [reply db/migrations/20240802044339_player_use_user_id_over_username.go:34]: That's a good question... I don't think so. Well, you could do something like:
```sql
ifnull((select id from user where user_name = player.user_name), 'UNKNOWN_USERNAME'),
```
And then:
```sql
delete from player_dg_tmp where user_id = 'UNKNOWN_USERNAME';
```

Comment (kgarner7) [reply db/migrations/20240802044339_player_use_user_id_over_username.go:34]: I'll give that a shot, thanks! As an aside, is there a way to test migrations (not manually)?

File: model/player.go (hunk 4 above)
Comment (deluan) [reply model/player.go:29]: Ah, I see. What I usually do in these cases is something like this:
```golang
var repo *playerRepository
repo = NewPlayerRepository(ctx, database).(*playerRepository)
```
This avoids changing the "production" code just to satisfy the tests. Sometimes it is inevitable, but I strive to keep the prod code clean

File: db/migrations/20240802044339_player_use_user_id_over_username.go (hunk 1 above)
Comment (deluan) [reply db/migrations/20240802044339_player_use_user_id_over_username.go:34]: I usually test it manually, as they are relevant only once in the project's lifetime and should not be modified any time after being committed (unless they are written in Go and you need to change method signatures and such)

File: persistence/player_repository_test.go (hunk 5 above)
Comment (kgarner7) [reply persistence/player_repository_test.go]: Yeah, I wasn't sure why it wasn't enabled across the board (e.g. if it was a test setup choice). Fixed!
