### PR TITLE
fix(authProvider.js) fix cacheUndefined bug - #901

### LINKED ISSUE #901: Bug: Encounter "ReferenceError: caches is not defined" error in console
* Version: 0.41.0
* Testing Environment: Raspberry Pi 4, Raspbian, docker
* Browser: Brave 1.21.77 (Chromium 89.0.4389.90) and Firefox 86.0.1

After the service startup, it's hanging on loading page, and the following error appear in brave browser's console:

```
Uncaught (in promise) ReferenceError: caches is not defined
    at ce (authProvider.js:102)
    at Object.logout (authProvider.js:62)
    at useLogout.js:44
    at CoreAdminRouter.js:89
    at CoreAdminRouter.js:43
    at Object.throw (CoreAdminRouter.js:24)
    at s (CoreAdminRouter.js:16)
```

image

Then I test it in firefox, it's function normally:

image

After doing some research, I find out that: **Chrome and Safari only expose `CacheStorage` to the windowed context over HTTPS** (Ref: https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage), so it's failed since I've not setup https yet.

I consider this as a bug since I always test the functionality of the service before doing some advanced stuffs (reverse proxy, https...etc), so I think it's abnormally to have this error and hope this can be fixed.

### PR DESCRIPTION
**Pull request by aldrinjenson**
Closes #901 

### Description
- The cache storage is not available to chromium based browsers in Android
- so throws up error when trying to delete it (the error happens only for chromium based browsers in android)

 ### Change Made
- added a check to see if cache is available before trying to delete it

#### Before
errorLogMain
#### After
fix

Related to #906

### CODE REVIEW

File: ui/src/authProvider.js [hunk 1]
```diff
@@ -99,9 +99,10 @@ const removeItems = () => {
 }
 
 const clearServiceWorkerCache = () => {
-  caches.keys().then(function (keyList) {
-    for (let key of keyList) caches.delete(key)
-  })
+  window.caches &&
```
Comment (aldrinjenson) [inline ui/src/authProvider.js:102]: Just putting (caches&&...) threw up error in chrome android. 
window.caches works fine tho.

**Comment by deluan** [comment]
Hey @certuna, how do you feel about merging this quick fix?

**Review by deluan — APPROVED** [review]
LGTM. Thanks!
