### PR TITLE
fix(persistence): Update play_date on scrobble only when newer - #2262

### LINKED ISSUE #2262: [Bug]: Scrobble with earlier time shouldn't override last play date
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3

### Current Behavior

When using Subsonic API to scrobble with a time, that time is always saved as last played time, even if it's earlier than the existing last played time. 

### Expected Behavior

The last played time should only be updated if the time is later.

### Steps To Reproduce

_No response_

### Environment

```markdown
(I'm using my own cli program to test the API behavior.)
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

### PR DESCRIPTION
**Pull request by upsuper**
Closes #2262

## Description

Update play_date on scrobble only when newer

## Changes

Make `annotation.play_date` set to `max` of the existing value and the new value.

## Screenshots or Videos

(None)

## Related Issues and Pull Requests(if any)

(None)

### CODE REVIEW

File: persistence/mediafile_repository_test.go [hunk 1]
```diff
@@ -158,6 +158,31 @@ var _ = Describe("MediaRepository", func() {
 			Expect(mf.PlayCount).To(Equal(int64(1)))
 		})
 
+		It("preserves play date iff provided date is older", func() {
```
Comment (deluan) [inline persistence/mediafile_repository_test.go:161]: typo: "...date _if_ provided..."

**Review by deluan — CHANGES_REQUESTED** [review]
LGTM, just a small typo. Thanks!

File: persistence/mediafile_repository_test.go (hunk 1 above)
Comment (upsuper) [reply persistence/mediafile_repository_test.go:161]: Not a typo. "iff" means "if and only if", so the test checks both that it updates when the time is newer and that it doesn't when older.

Comment (deluan) [reply persistence/mediafile_repository_test.go:161]: Sorry, but I rather have the test descriptions as plain English, so it is better to just write "if and only if".

Comment (upsuper) [reply persistence/mediafile_repository_test.go:161]: I think "iff" is a common abbreviation of "if and only if" (see e.g. [Wikipedia](https://en.wikipedia.org/wiki/If_and_only_if)) but if you insist then sure.

Comment (upsuper) [reply persistence/mediafile_repository_test.go]: Oh and it's actually an English word https://www.merriam-webster.com/dictionary/iff

**Review by deluan — APPROVED** [review]
