### PR TITLE
Fixes play icon color in "Light" theme

### LINKED ISSUE #960: Play icon became dark on "light" theme.
### Description

The play icon that appears on top of album covers needs to always be forced to be white, and not "inherit" (default). This is the expected appearence:

Correct, from the demo server (version 0.41.0):
Screen Shot 2021-04-01 at 11 46 22 PM

Wrong, from master:
Screen Shot 2021-04-01 at 11 47 01 PM

### Expected Behaviour

The play button must always be white when displayed over an album cover.

### Steps to reproduce

1. Select "Light" theme. 
2. Go to an Album List
3. Hover the mouse over an album

### Platform information

 - Navidrome version: latest from master
 - Browser and version: all browsers
 - Operating System: all OSes

### Additional information

The play button has to be "white" **ONLY** on album covers, in other places where it appears in the UI it is correct.

### PR DESCRIPTION
**Pull request by shishir610**
Fixes #960 
Displays play icon appropriately for different themes

Light: 
image

Dark: 
image

Spotify-ish:
image

### CODE REVIEW

File: ui/src/common/PlayButton.js [hunk 1]
```diff
@@ -46,8 +48,7 @@ export const PlayButton = ({ record, color, size, ...rest }) => {
         playAlbum(record)
       }}
       aria-label="play"
-      className={classes.icon}
-      {...rest}
+      className={theme === 'Light' ? classes.icon : rest.className}
```
Comment (deluan) [inline ui/src/common/PlayButton.js:51]: We don't want to check if the light theme is selected. What if we introduce another theme based on "Light", but with a different name?

The solution is to set the default color of the button to white, but it can be overridden by a any theme using the `NDAlbumGridView.albumPlayButton` class (as in the _Spotify-ish_ theme)

**Review by deluan — CHANGES_REQUESTED** [review]
Thanks, but check my comment below.

File: ui/src/common/PlayButton.js (hunk 1 above)
Comment (shishir610) [reply ui/src/common/PlayButton.js]: I understand. I removed a lot of unnecesary code between `AlbumGridView.js` and `PlayButton.js` and included `albumPlayButton: { color: 'white' }` instead which fixes the issue at hand.

File: ui/package.json [hunk 2]
```diff
@@ -33,7 +33,7 @@
     "@testing-library/react-hooks": "^5.1.0",
     "@testing-library/user-event": "^13.0.7",
     "css-mediaquery": "^0.1.2",
-    "prettier": "^2.2.1"
+    "prettier": "2.2.1"
```
Comment (deluan) [inline ui/package.json:36]: Why you changed the `prettier` dependency? Please revert `package.json` and `package-lock.json`

**Review by deluan — CHANGES_REQUESTED** [review]
Yes, that's more like it, thanks! Please check the comment below.

File: ui/package.json (hunk 2 above)
Comment (shishir610) [reply ui/package.json:36]: Oh, I'm sorry. I must have accidently ran a npm command. Reverting.

Comment (deluan) [reply ui/package.json]: Ideally the fix would be to rebase interactively your branch (`git rebase -i`) and remove the unwanted changes, instead creating another commit reverting the files. But as I'm gonna squash the PR it does not really matter. Anyway, take a look at how rebase interactively works.

File: ui/src/common/PlayButton.js [hunk 3]
```diff
@@ -5,16 +5,8 @@ import { IconButton } from '@material-ui/core'
...
 
-const useStyles = makeStyles({
-  icon: {
-    color: (props) => props.color,
-  },
-})
-
-export const PlayButton = ({ record, color, size, ...rest }) => {
-  const classes = useStyles({ color })
+export const PlayButton = ({ record, size, className }) => {
```
Comment (deluan) [inline ui/src/common/PlayButton.js:9]: You should remove `color` from the `propTypes` below as well (line 51), and add `className`. Can you also mark `record` as `.isRequired`, please?

**Review by deluan — CHANGES_REQUESTED** [review]

File: ui/package.json (hunk 2 above)
Comment (shishir610) [reply ui/package.json]: I got it. I'll look into how rebase interactively. Thanks a lot!

File: ui/src/common/PlayButton.js (hunk 3 above)
Comment (shishir610) [reply ui/src/common/PlayButton.js:9]: Making these necessary changes and pushing.

**Comment by deluan** [comment]
Thanks!
