### PR TITLE
Recursively refresh playlist tracks within smart playlist rules

### LINKED ISSUE #3017: [Bug]: Smart playlists do not refetch tracks from child smart playlists used in rules
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.52.0 (92a98cd5)

### Current Behavior

When fetching a smart playlist that uses the `inPlaylist`or `notInPlaylist` rules, the child smart playlists from these rules are not refreshed first. This means if the child playlists use a `random` selection of songs with a `limit`, the main smart playlist will always refresh with the same selection of songs, unless the child playlists are manually refreshed beforehand.

### Expected Behavior

When fetching a smart playlists, all smart playlist dependencies from the defined rules should also be refreshed to ensure a new set of random songs is selected.

### Steps To Reproduce

1. In this scenario, the music folder has a 6 tracks, 2 of which have a comment with the text "A" and the other 2 with the text "B". The following smart playlists are also present.

SmartPlaylistA (`4b186cad-1368-41c7-83c1-f5198da684d3`)
```json
{
    "any": [
        {
            "contains": {
                "comment": "A"
            }
        }
    ],
    "sort": "random",
    "limit": 2
}
```

SmartPlaylistB (`c7f71bd2-35d4-4055-bc3b-555a884b1384`)
```json
{
    "any": [
        {
            "contains": {
                "comment": "B"
            }
        }
    ],
    "sort": "random",
    "limit": 2
}
```

MainSmartPlaylist
```json
{
    "any": [
        {
            "inPlaylist": {
                "id": "4b186cad-1368-41c7-83c1-f5198da684d3"
            }
        },
        {
            "inPlaylist": {
                "id": "c7f71bd2-35d4-4055-bc3b-555a884b1384"
            }
        }
    ],
    "sort": "random"
}
```

2. When accessing `MainSmartPlaylist` via the Navidrome UI or a client using the API, refreshing will not change the song selections. The same two `A` songs and `B` songs are always present, so the remaining two songs are never in the playlist unless `SmartPlaylistA`/`SmartPlaylistB` are manually refreshed.

### Environment

```markdown
- OS: Ubuntu 22.04
- Browser: Firefox 125.02
- Client: Amperfy (on iOS)
```

### How Navidrome is installed?

Docker

### Configuration

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

### PR DESCRIPTION
**Pull request by reillymc**
Fixes #3017 

This PR ensure that when a smart playlist is refreshed, the playlists used in its rules also have their tracks refreshed first.

This is my first time diving into the Navidrome codebase and using the Go language, so if there is anything I need to do to improve the code here please let me know and I'll be happy to fix it up!

### CODE REVIEW

**Review by deluan — CHANGES_REQUESTED** [review]
Good job for a first Go AND Navidrome contribution. I admit this codebase can be daunting.

Anyway, thanks and take a look at my comments below.

File: model/criteria/operators.go [hunk 1]
```diff
@@ -36,6 +40,10 @@ func (any Any) MarshalJSON() ([]byte, error) {
 	return marshalConjunction("any", any)
 }
 
+func (any Any) ChildPlaylistIds() (ids []string) {
+	return extractPlaylistIds(any, ids)
```
[the remark this answers is not in the document]
Comment (reillymc) [reply model/criteria/operators.go:44]: Ah thank you for that - definitely agree its nicer not to mutate the arguments.

File: model/criteria/operators.go [hunk 2]
```diff
@@ -275,3 +283,29 @@ func inList(m map[string]interface{}, negate bool) (sql string, args []interface
 		return "media_file.id IN (" + subQText + ")", subQArgs, nil
 	}
 }
+
+func extractPlaylistIds(inputRule interface{}, ids []string) []string {
+	var id string
```
[the remark this answers is not in the document]
Comment (reillymc) [reply model/criteria/operators.go:288]: Thanks, I think this should be addressed now by using a named return type instead of an argument. Whoops!

File: model/criteria/operators.go [hunk 3]
```diff
@@ -275,3 +283,29 @@ func inList(m map[string]interface{}, negate bool) (sql string, args []interface
...
+			ids = extractPlaylistIds(rules, ids)
+		}
+	case InPlaylist:
+		if id, ok = rule["id"].(string); ok {
+			ids = append(ids, id)
+		}
+	case NotInPlaylist:
+		if id, ok = rule["id"].(string); ok {
+			ids = append(ids, id)
+		}
```
[the remark this answers is not in the document]
Comment (reillymc) [reply model/criteria/operators.go:307]: Ah yes, I initially tried to do this however I hit an error. From reading up on it, using multiple cases in a type switch doesn't narrow the type of rule to `Any`/`All` but instead it remains as `interface{}` and I am then unable iterate over or index it. I wasn't able to find a nice solution unfortunately so I had to leave it verbose. Happy to fix up if there's a trick I've missed.

File: persistence/playlist_repository.go [hunk 4]
```diff
@@ -219,6 +219,18 @@ func (r *playlistRepository) refreshSmartPlaylist(pls *model.Playlist) bool {
...
+
+	// If the playlist depends on other playlists, recursively refresh them first
+	childPlaylistIds := rules.ChildPlaylistIds()
+	for _, id := range childPlaylistIds {
+		childPls, err := r.Get(id)
+		if err != nil {
+			log.Error(r.ctx, "Error loading child playlist", "id", pls.ID, "childId", id, err)
+			return false
+		}
+		r.refreshSmartPlaylist(childPls)
```
[the remark this answers is not in the document]
Comment (reillymc) [reply persistence/playlist_repository.go:231]: Definitely a fair point on performance. I did a little bit of testing that I'll include below. I could only manage to grab ~2500 songs for my test library - not sure what large libraries/playlists are in terms of how Navidrome is used but hopefully this is some useful data to go off! I used the logger to get the times from the running dev server.


**Test 1:**
A smart playlist with two playlist dependencies. Each picking a random 100 songs from a library of ~2500

| Playlist                      | Run 1 | Run 2 | Run 3 | Average |
| ----------------------------- | ----- | ----- | ----- | ------- |
| Sub-playlist A                | 8.5   | 7.2   | 5.7   | 7.1     |
| Sub-playlist B                | 7.9   | 13.4  | 6.5   | 9.3     |
| Main playlist with changes    | 27.4  | 32.9  | 22.5  | 27.6    |
| Main playlist without changes | 5.6   | 27.2  | 4.5   | 12.4    |

Difference of ~15.2ms to fetch main playlist. This aligns with the ~16.4 total milliseconds taken to refresh the sub playlists.



**Test 2:** 
A smart playlist with two playlist dependencies. Each picking a random 1000 songs from a library of ~2500

| Playlist                      | Run 1 | Run 2 | Run 3 | Average |
| ----------------------------- | ----- | ----- | ----- | ------- |
| Sub-playlist A                | 10.0  | 8.6   | 10.0    | 9.5     |
| Sub-playlist B                | 8.8   | 8.5   | 7.7   | 8.3     |
| Main playlist with changes    | 43.7  | 45    | 43    | 43.9    |
| Main playlist without changes | 25.9  | 25.3  | 23.4  | 24.9    |

Difference of ~19ms to fetch main playlist. This aligns with the ~17.8 total milliseconds taken to refresh the sub playlists.


Overall the fetching time for the sub-playlists is basically added onto the main playlist which is expected. The additional time is pretty minor (at least at this scale) for the total refresh time to the user; however it does basically double the overall time which could be an issue at a much larger scale.

An alternative may be to map these recursive refreshes into the one SQL statement directly as sub-queries (although this is probably a bit beyond what I can wrangle, at least right now).

Otherwise perhaps a boolean flag on the playlist to indicate whether it should use the 'dynamic refresh' of sub-playlists functionality.

**Comment by reillymc** [comment]
> Good job for a first Go AND Navidrome contribution. I admit this codebase can be daunting.
> 
> Anyway, thanks and take a look at my comments below.

Thanks for taking a look! I'd be interested in your thoughts on the performance side and if you think this will be a trade-off you'd be willing to make. This ability is the last thing from my old iTunes playlists that I haven't been able to bring over to Navidrome but otherwise they have been fantastic!

File: persistence/playlist_repository.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (deluan) [reply persistence/playlist_repository.go:231]: Can you post here the NSP files you used to run this tests? I can run it agains my 83K songs library.

File: model/criteria/operators.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (deluan) [reply model/criteria/operators.go]: Hummm, yeah I think you are right. We can leave it like that for now.

I'll have to do a big refactor in Smart Playlists, due to the database schema changes in #2709, so if we merge this I'll think a bit about ways to remove this duplication.

File: persistence/playlist_repository.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (reillymc) [reply persistence/playlist_repository.go:231]: Wow thats a serious test library...
Here are my nsp files (as json files so github would allow the upload). Basically I used a bulk tagger to set half my library with a comment of A and the other half with B.

[mainPlaylist.json](https://github.com/user-attachments/files/15906337/mainPlaylist.json)
[selectionB.json](https://github.com/user-attachments/files/15906339/selectionB.json)
[selectionA.json](https://github.com/user-attachments/files/15906340/selectionA.json)

**Comment by deluan** [comment]
One more thing: It is missing tests. Can you please add tests for the logic you implemented?

File: conf/configuration.go [hunk 5]
```diff
@@ -300,6 +301,7 @@ func init() {
 	viper.SetDefault("enableartworkprecache", true)
 	viper.SetDefault("autoimportplaylists", true)
 	viper.SetDefault("playlistspath", consts.DefaultPlaylistsPath)
+	viper.SetDefault("smartPlaylistRefreshTimeout", 5*time.Second)
```
Comment (deluan) [inline conf/configuration.go:304]: Hey, thanks for this. Can you make the value all lowercase, like `smartplaylistrefreshtimeout`? I think Viper has an issue with this.

File: model/criteria/criteria_test.go [hunk 6]
```diff
@@ -89,4 +90,94 @@ var _ = Describe("Criteria", func() {
 		gomega.Expect(newObj.OrderBy()).To(gomega.Equal("random() asc"))
 	})
 
+	It("extracts all child smart playlist IDs from All expression criteria", func() {
+		var topLevelInPlaylistID = uuid.New().String()
```
Comment (deluan) [inline model/criteria/criteria_test.go:94]: Nitpick: please use this style:
```suggestion
		topLevelInPlaylistID := uuid.NewString()
```

File: conf/configuration.go (hunk 5 above)
Comment (reillymc) [reply conf/configuration.go:304]: Oops my bad - should have picked that up from the other items. All fixed!

File: persistence/playlist_repository_test.go [hunk 7]
```diff
@@ -143,5 +145,33 @@ var _ = Describe("PlaylistRepository", func() {
...
+				Expect(err).ToNot(HaveOccurred())
+
+				_, err = repo.GetWithTracks(parentPls.ID, true)
+				Expect(err).ToNot(HaveOccurred())
+
+				// Check that the nested playlist was refreshed by parent get by verifying evaluatedAt is updated since first nestedPls get
+				nestedPlsAfterParentGet, err := repo.Get(nestedPls.ID)
+				Expect(err).ToNot(HaveOccurred())
+
+				Expect(*nestedPlsAfterParentGet.EvaluatedAt).To(BeTemporally(">", *nestedPlsRead.EvaluatedAt))
```
Comment (sammbeller) [inline persistence/playlist_repository_test.go:173]: I think  it would be better to update the nested playlist and check the updated value is referenced correctly in the parent playlist, which is a more specific test about the expected behavior of the used `Criteria` that would additionally verify that this change does what it is expected to do. Does that make sense?

File: persistence/playlist_repository.go [hunk 8]
```diff
@@ -198,8 +199,8 @@ func (r *playlistRepository) selectPlaylist(options ...model.QueryOptions) Selec
 }
 
 func (r *playlistRepository) refreshSmartPlaylist(pls *model.Playlist) bool {
-	// Only refresh if it is a smart playlist and was not refreshed in the last 5 seconds
-	if !pls.IsSmartPlaylist() || (pls.EvaluatedAt != nil && time.Since(*pls.EvaluatedAt) < 5*time.Second) {
+	// Only refresh if it is a smart playlist and was not refreshed within the interval provided by the refresh timeout config
+	if !pls.IsSmartPlaylist() || (pls.EvaluatedAt != nil && time.Since(*pls.EvaluatedAt) < conf.Server.SmartPlaylistRefreshTimeout) {
```
Comment (sammbeller) [inline persistence/playlist_repository.go:203]: nit: this name is confusing, this isn't really a timeout

**Review by sammbeller — COMMENTED** [review]
couple nits, obviously feel free to ignore

File: persistence/playlist_repository_test.go (hunk 7 above)
Comment (deluan) [reply persistence/playlist_repository_test.go:173]: Yes, it does. This tests seems to assume the resolution of the Smart Playlist rules works as expected, so it only checks if the nested playlist was updated or not. I think it is a valid test. 

IMO, what you are suggesting is more like an integration test, that checks all these parts working together, and we would need to setup data in the MediaFile repository for it to work. Of course it has its value, but requires a different setup. I'm personally ok with this test as is.

File: persistence/playlist_repository.go (hunk 8 above)
Comment (deluan) [reply persistence/playlist_repository.go:203]: Agree. I'm changing it to `SmartPlaylistRefreshDelay`, and changing the default to 1 minute.

**Review by deluan — APPROVED** [review]
Fixed small nits, hope you agree with my changes :)

Merging it now.

File: persistence/playlist_repository_test.go (hunk 7 above)
Comment (sammbeller) [reply persistence/playlist_repository_test.go]: More as a matter of learning about your testing principles in this project I would like to make the following comment. The test as written is looking at behavior internal to the unit under test, specifically the line including the conditional that the delay is included on. We're already in the data layer so I'm not sure scope is increased that much by touching another repo. At the same time, there are other ways to test this exact behavior such as ensuring that `refreshSmartPlaylist` is called on all relevant child playlists. In general I don't think this side-effect testing test is super valuable.

If this discussion has outlived its usefulness, please let me know. As I said I'm just trying to learn about how this project thinks about testing.

**Comment by reillymc** [comment]
Looks great! Thanks for all your help to get this merged!
