### PR TITLE
Fix PWA notification toolbar color

### LINKED ISSUE #1063: [PWA] status bar doesn't match theme color
I tried the new spotify-ish theme, i find it really great, but when I install Navidrome as a PWA... The status bar on top of my phone is blue... 🤔 

OfaKePN

### PR DESCRIPTION
**Pull request by Dnouv**
As mentioned in issue #1063, in the PWA, the color of the notification bar was not similar to the theme; in this PR, I have tried to fix issue #1063 by setting the toolbar color as the theme's palette `light` color( if it is defined or else to the `main` color of the palette). Please find the screenshots of the app after changes, (Fixes #1063 )

In Spotify-ish theme:
br_509

In Extra-Dark theme:
br_509

In Ligera theme:
br_509

Feedbacks are most welcomed. Thank you!

### CODE REVIEW

File: ui/src/App.js [hunk 1]
```diff
@@ -30,6 +30,7 @@ import config from './config'
 import { setDispatch, startEventStream } from './eventStream'
 import { HotKeys } from 'react-hotkeys'
 import { keyMap } from './hotkeys'
+import ChangeColor from './common/PWA'
```
Comment (deluan) [inline ui/src/App.js:33]: I think this component should leave in the root (`ui/src`) as it is only used by the `App.js` file, not really a "common" component. Also, I'd rename `PWA.js` to `ChangeColor` as it is the only component exported by the file

File: ui/src/common/PWA.js [hunk 2]
```diff
@@ -0,0 +1,21 @@
+import useCurrentTheme from '../themes/useCurrentTheme'
+
+const ChangeColor = () => {
+  const theme = useCurrentTheme()
+  const query = document.querySelector("meta[name='theme-color']")
+
+  try {
+    const color =
```
Comment (deluan) [inline ui/src/common/PWA.js:8]: Shouldn't this logic be inside a `useEffect` hook, to avoid it running multiple times? Maybe it could be just a function, called from a `useEffect` hook inside the `Admin` component

**Review by deluan — CHANGES_REQUESTED** [review]
Thanks for taking a stab at this, and for testing with multiple themes. Take a look at the comments below

File: ui/src/common/PWA.js (hunk 2 above)
Comment (Dnouv) [reply ui/src/common/PWA.js]: Thanks for your review; I have removed the if loop and used the `useEffect` hook.

**Comment by deluan** [comment]
Hey @Dnouv I converted the component into a hook, as it was really not a component and not rendering anything. Thanks for the PR!

**Comment by deluan** [comment]
By the way, I'm seeing this error below in the console referring the `Ligera` theme. Doesn't seem to be related to this, but can you please take a look? Thanks!

```
Material-UI: You are trying to override a style that does not exist.
Fix the `&:hover` key of `theme.overrides.MuiDrawer`. 
    at WithStyles (http://localhost:4533/static/js/0.chunk.js:44774:31)
    at Sidebar (http://localhost:4533/static/js/0.chunk.js:135478:24)
    at main
    at div
    at div
    at LayoutWithoutTheme (http://localhost:4533/static/js/0.chunk.js:134273:24)
    at WithStyles (http://localhost:4533/static/js/0.chunk.js:44774:31)
    at C (http://localhost:4533/static/js/0.chunk.js:353348:37)
    at ConnectFunction (http://localhost:4533/static/js/0.chunk.js:350632:75)
    at ThemeProvider (http://localhost:4533/static/js/0.chunk.js:43476:24)
    at Layout (http://localhost:4533/static/js/0.chunk.js:134391:26)
    at div
    at HotKeysWrapper (http://localhost:4533/static/js/0.chunk.js:182510:5)
    at HotKeysEnabled (http://localhost:4533/static/js/0.chunk.js:192231:7)
    at push../src/layout/Layout.js.__webpack_exports__.default (http://localhost:4533/static/js/main.chunk.js:9798:88)
    at Route (http://localhost:4533/static/js/0.chunk.js:353091:29)
    at Switch (http://localhost:4533/static/js/0.chunk.js:353293:29)
    at div
    at CoreAdminRouter (http://localhost:4533/static/js/0.chunk.js:98879:87)
    at Route (http://localhost:4533/static/js/0.chunk.js:353091:29)
    at Switch (http://localhost:4533/static/js/0.chunk.js:353293:29)
    at CoreAdminUI (http://localhost:4533/static/js/0.chunk.js:99095:15)
    at AdminUI
    at Router (http://localhost:4533/static/js/0.chunk.js:352726:30)
    at ConnectedRouter (http://localhost:4533/static/js/0.chunk.js:55978:7)
    at ConnectedRouterWithContext (http://localhost:4533/static/js/0.chunk.js:56101:25)
    at ConnectFunction (http://localhost:4533/static/js/0.chunk.js:350632:75)
 ```

**Comment by Dnouv** [comment]
Thanks a lot, @deluan, for the review, and about this error, I will create a PR to fix it.
