### PR TITLE
fix(scanner): sort_artist_name to be used when  indexing performers if PreferSortTag is true

### LINKED ISSUE #3285: [Bug]: Index value in Subsonic getArtists API's response is not created using sort_artist_name.
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.53.1

### Current Behavior

The value of index returned by Subsonic getArtists API is as follows.
 
|artist                |  index       |    sort_artist_name 
|----------------|-----------|------------------------------------------
|小倉唯             |  小            |   Ogura Yui (or おぐら ゆい)
|小松未可子     |   小            |   Komatsu Mikako (or こまつ みかこ)
|小枝                |   小            |   Sae (or さえ)

Remark configration: IndexGroups includes "小"

### Expected Behavior

When the value of setting PreferSortTags is true, the index value should be created using the value of sort_artist_name as follows.

|artist                |  index       |    sort_artist_name 
|----------------|-------------|------------------------------------------
|小倉唯             |  O (or お)  |   Ogura Yui (or おぐら ゆい)
|小松未可子     |   K (or こ)  |   Komatsu Mikako (or こまつ みかこ)
|小枝                |   S (or さ)  |   Sae (or さえ)

Remark configration: IndexGroups includes "O", "K", "S" (or "お", "こ", "さ")

### Steps To Reproduce

1. start navidrome
2. run scan (If necessary)
3. call Subsonic getArtists API 
   https://example.com/rest/getArtists?u=xxx&p=xxx&v=xxx&c=xxx
4. check the response 

### Environment

```markdown
- OS:ubuntu 22.04
- Browser: Firefox (Browser irrelevant)
- Client:  web
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
IndexGoups = "A B C D E F G H I J K L M N O P Q R S T U V W X-Z(XYZ) [Unknown]([) 小"
PreferSortTags = true
```

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

### PR DESCRIPTION
**Pull request by naiar**
Closes #3285

Description

Navidrome is modified so that when the Subsonic getArtists API is executed, if the setting PreferSortTags is true, the value of index should be created using sort_artist_name.

Changes
- getIndexKey: Fixed the process of getting the original value of index.
- GetIndex: Fix sorting when retrieving records from table artist so that all artists with equal index values are included in the same index tag.
- Add test of getIndexKey. 
- Modify test of GetIndex.

### CODE REVIEW

File: persistence/export_test.go [hunk 1]
```diff
@@ -0,0 +1,5 @@
+package persistence
+
+// Definitions for testing private methods
+
+var GetIndexKey = (*artistRepository).getIndexKey
```
Comment (deluan) [inline persistence/export_test.go:5]: Nice trick!

**Comment by deluan** [comment]
Thanks for this, good catch! The PR looks good, just made a small change.
