### PR TITLE
fix(ui): save play mode for player - 3019

### LINKED ISSUE #3019: [Bug]: In webplayer, I have changed playlist to repeat, after refresh browser, it is still "in order"
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

latest

### Current Behavior

In webplayer, I have changed playlist to repeat, after refresh browser, it is still "in order"

### Expected Behavior

If I changed playlist to repeat, the change should be saved in server. 
or add configuration in "edit playlist" , user can changes default playlist is "repeat" or "in order"

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
- Browser:
- Client:
```

### How Navidrome is installed?

Docker

### Configuration

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

### PR DESCRIPTION
**Pull request by kgarner7**
Resolves #3019.

### CODE REVIEW

File: ui/src/audioplayer/Player.js [hunk 1]
```diff
@@ -93,6 +95,7 @@ const Player = () => {
     () => ({
       theme: playerTheme,
       bounds: 'body',
+      playMode: localStorage.getItem(PLAYMODE_KEY),
```
Comment (deluan) [inline ui/src/audioplayer/Player.js:98]: Ideally we would store this info in the Redux store, and add the selector to the store persistence, in https://github.com/navidrome/navidrome/blob/25d6b8d4956aa53bc53afdacfc9540e73a038355/ui/src/store/createAdminStore.js#L58-L67

This would be the ideal implementation in the current UI. But, as we are moving away from both Redux and this player in the next UI, and the current one is basica legacy at this point, I'm ok with this implementation. Unless you want to implement it using Redux :P

**Review by deluan — COMMENTED** [review]
See my comment and let me know.

**Comment by deluan** [comment]
Awesome! Thanks!
