### PR TITLE
I876: Song Playtime display fix

### LINKED ISSUE #876: Improper display of song play time
The song play time in the player is not completely visible on some screen sizes, it can be seen in the attached screenshot that the duration 00:00-----01:02 is not completely visible the only visible play time is as "00-----01"
The issue screen:
navid_bug

Expected duration screen:
navid_bugnv

@deluan I would like to work on this issue, could you have a look.
Thank you!

### PR DESCRIPTION
**Pull request by Dnouv**
As mentioned in issue #876,  the song duration was not displayed correctly; the issue was in the `breakpoint-width`, it is now fixed. Here is the screenshot of the fixed page. (Fix #876 )
navid_sif
Feel free to provide feedback. Thank you!

### CODE REVIEW

**Comment by deluan** [comment]
I was still able to "break" the song duration:
Screen Shot 2021-03-22 at 11 38 31 PM

**Comment by Dnouv** [comment]
@deluan, here is the screen recording; the issue is not visible; please have a look and review.

https://user-images.githubusercontent.com/61188295/112103126-5118c100-8bcf-11eb-88aa-53e0b291148a.mp4

Thank You!

**Comment by deluan** [comment]
I don't see it working:


https://user-images.githubusercontent.com/331353/112151887-17888b80-8bb8-11eb-9d23-ba2f90db8179.mp4

**Comment by Dnouv** [comment]
@deluan, sorry for the trouble; the issue is now resolved. In the previous commit, the issue was fixed only on the Album details page; that is why the issue was still there on the Album grid page, but it is fixed now for both of the pages.
Please once again have a review.
Thank you!

**Comment by Dnouv** [comment]
@deluan, sorry to interrupt you, I understand you may be busy, but could you please review it again.
Thank you!

**Review by deluan — COMMENTED** [review]
LGTM. Please check the comment bellow.

**Comment by Dnouv** [comment]
@deluan, sorry, but I could not find the comments.

File: ui/src/album/AlbumDetails.js [hunk 1]
```diff
@@ -25,7 +25,7 @@ const useStyles = makeStyles((theme) => ({
   root: {
     [theme.breakpoints.down('xs')]: {
       padding: '0.7em',
-      minWidth: '24em',
+      minWidth: '20em',
```
Comment (deluan) [inline ui/src/album/AlbumDetails.js:28]: Is it still needed?

File: ui/src/audioplayer/Player.js [hunk 2]
```diff
@@ -31,6 +31,11 @@ const useStyle = makeStyles((theme) => ({
   },
   player: {
     display: (props) => (props.visible ? 'block' : 'none'),
+    '@media screen and (max-width:810px)': {
+      '& .progress-bar-content': {
+        display: 'none!important',
```
Comment (deluan) [inline ui/src/audioplayer/Player.js:36]: Can it be done without the `!important`?

**Review by deluan — COMMENTED** [review]
GH lost my comments... :P Here they are:

File: ui/src/audioplayer/Player.js (hunk 2 above)
Comment (Dnouv) [reply ui/src/audioplayer/Player.js:36]: Sure, it could be done without `!important`. I will remove it in the next commit.

File: ui/src/album/AlbumDetails.js (hunk 1 above)
Comment (Dnouv) [reply ui/src/album/AlbumDetails.js:28]: Yeah, it is still required. Is there any issue with this, please let me know

**Comment by deluan** [comment]
Please fix the conflicts so I can do a final test and merge if everything is OK

**Comment by Dnouv** [comment]
@deluan, I have resolved the conflicts, so could you please review this PR?

**Comment by deluan** [comment]
>  the issue is now resolved. In the previous commit, the issue was fixed only on the Album details page; that is why the issue was still there on the Album grid page, but it is fixed now for both of the pages.

Hey @Dnouv, just to be sure: Your change will work on **all** pages, not just the two album pages, right?

**Comment by Dnouv** [comment]
For sure, it is going to work on all pages. Thanks for your review, @deluan.

**Comment by deluan** [comment]
I think it is better to hide the volume bar instead of the progress bar, or else we lose the name of the song being played:
Screen Shot 2021-04-20 at 9 11 47 PM

We should also make the breakpoint for `isDesktop` in this file to the same number (810).

**Comment by Dnouv** [comment]
Ok, thanks for your review, @deluan; I will make the required changes.

**Comment by Dnouv** [comment]
@deluan, I have made the required changes; please have a review.
Thank you!
