### PR TITLE
fix(UI): Warn if track is already present when adding to playlist - 1604

### LINKED ISSUE #1604: Warn if track is already present when adding to playlist
When browsing your collection and adding tracks to playlists, it is easy to accidentally add the same track twice (or more) to a given playlist.

When I select a track and click **add to playlist**, it should say "This track is already present, are you sure you want to add?"

### PR DESCRIPTION
**Pull request by joaomqc**
Closes #1604 

Fixes previously existing functionality of showing a warning if a track is already present when adding it to a playlist.

Behavior when skipping a song already in a playlist

skip

Behavior when adding a song already in a playlist

add

### CODE REVIEW

File: ui/src/dialogs/AddToPlaylistDialog.js [hunk 1]
```diff
@@ -44,34 +46,37 @@ export const AddToPlaylistDialog = () => {
...
+        })
+    } else {
+      notify('message.songsAddedToPlaylist', 'info', { smart_count: 0 })
+    }
   }
 
   const checkDuplicateSong = (playlistObject) => {
-    dataProvider
-      .getOne('playlist', { id: playlistObject.id })
+    httpClient(`${REST_URL}/playlist/${playlistObject.id}/tracks`)
```
Comment (deluan) [inline ui/src/dialogs/AddToPlaylistDialog.js:70]: Is there a reason for switching from `dataProvider` to `httpClient`? Ideally we want to use `dataProvider` as much as possible. You can access a playlist's track by using the `playlistTrack` resource (with `playlist_id` filter). Example: https://github.com/navidrome/navidrome/blob/d3e142233b3f072df834c9f048996a2cdc783e47/ui/src/playlist/PlaylistActions.js#L45-L50

**Review by deluan — CHANGES_REQUESTED** [review]
Thanks for taking a stab at this. Looks good, but take a look at the comment below.

File: ui/src/dialogs/AddToPlaylistDialog.js (hunk 1 above)
Comment (joaomqc) [reply ui/src/dialogs/AddToPlaylistDialog.js:70]: I tried to do it that way, but ran into the issue of that messing with the track list on display. If I'm in a playlist and try to add a song from that playlist to another one, when I click on the name of the other playlist, the `dataprovider` updates the list in memory and causes a change to the list displayed.

You can see what I mean in this gif
dataprovider

Comment (deluan) [reply ui/src/dialogs/AddToPlaylistDialog.js:70]: Yeah, you are right. I wonder how this worked before... :/

Anyway, can you please fix the tests so I can merge this one? Thanks!

**Review by deluan — APPROVED** [review]
